In [1]:
import numpy as np

In [17]:
n = 13

# randomly generate mu
# randomly generate sigma

mu = np.random.normal(0, scale=20.0, size=n)

std = np.sqrt(np.random.normal(0, scale=10.0, size=n)**2)

In [19]:
mu, std

(array([ 10.34020663,  -5.32110325, -23.76501655,  -9.9471319 ,
         11.08306402,  28.44419468,  34.33795322,  -3.5271869 ,
         14.31617576,  -2.37601258,   3.10218378,  31.74930251,
         30.65958678]),
 array([ 6.14500234, 15.43086255,  3.95305606,  8.95857769,  5.82440163,
        10.0310225 ,  8.20700403,  8.16668611,  3.34533295,  9.30209542,
         7.54420077,  0.17705991, 13.322939  ]))

In [37]:
# generate code

s = 'normalized_f = [{}]\n'.format(', '.join([f'(f[{i}] - mu[{i}]) / std[{i}]' for i in range(n)]))


target_var_names = ["t_carrier_delay",
            "t_weather_delay",
            "t_nas_delay",
            "t_security_delay",
            "t_late_aircraft_delay"]

# generate some random variables to create "linear" model to predict
for name in target_var_names:
    s += '\n'
    lm = ' + '.join([f'normalized_f[{i}] * {val:.2f}' for i, val in zip(range(n), np.random.normal(loc=2, scale=3, size=n))])
    s += 'normalized_{} = {}\n'.format(name, lm)
    s += '{} = {}\n'.format(name,  'normalized_{} * {:.2f} + {:.2f}'.format(name,
                                                                    10.0 * np.random.normal(),
                                                                    5.0 * abs(np.random.normal())))
print(s)

normalized_f = [(f[0] - mu[0]) / std[0], (f[1] - mu[1]) / std[1], (f[2] - mu[2]) / std[2], (f[3] - mu[3]) / std[3], (f[4] - mu[4]) / std[4], (f[5] - mu[5]) / std[5], (f[6] - mu[6]) / std[6], (f[7] - mu[7]) / std[7], (f[8] - mu[8]) / std[8], (f[9] - mu[9]) / std[9], (f[10] - mu[10]) / std[10], (f[11] - mu[11]) / std[11], (f[12] - mu[12]) / std[12]]

normalized_t_carrier_delay = normalized_f[0] * 1.12 + normalized_f[1] * 4.49 + normalized_f[2] * 3.42 + normalized_f[3] * 4.28 + normalized_f[4] * 0.81 + normalized_f[5] * 5.13 + normalized_f[6] * 5.26 + normalized_f[7] * -0.07 + normalized_f[8] * -1.39 + normalized_f[9] * 2.74 + normalized_f[10] * -2.93 + normalized_f[11] * 4.81 + normalized_f[12] * 4.36
t_carrier_delay = normalized_t_carrier_delay * 4.06 + 1.48

normalized_t_weather_delay = normalized_f[0] * 1.84 + normalized_f[1] * -1.92 + normalized_f[2] * 2.59 + normalized_f[3] * -1.49 + normalized_f[4] * 9.29 + normalized_f[5] * 7.88 + normalized_f[6] * 1.11 + normalized_f[7] * 3.87 + 

In [23]:
i= 1


'(f[1] - mu[1]) / std[1]'

In [25]:
f = np.random.normal(0, scale=20.0, size=n)

In [26]:
normalized_f = [(f[0] - mu[0]) / std[0], (f[1] - mu[1]) / std[1], (f[2] - mu[2]) / std[2], (f[3] - mu[3]) / std[3], (f[4] - mu[4]) / std[4], (f[5] - mu[5]) / std[5], (f[6] - mu[6]) / std[6], (f[7] - mu[7]) / std[7], (f[8] - mu[8]) / std[8], (f[9] - mu[9]) / std[9], (f[10] - mu[10]) / std[10], (f[11] - mu[11]) / std[11], (f[12] - mu[12]) / std[12]]

In [27]:
normalized_f

[-0.023880441138122654,
 0.09221761273088569,
 6.1047679636474,
 1.4632219848547927,
 1.9422300088513167,
 -9.623320555685202,
 2.1705638973482544,
 -2.9436940670477414,
 -11.434306051184459,
 0.5254869136648129,
 1.648711325974819,
 -246.56034148045887,
 -0.6148549004322564]

In [38]:
mu.sum()

119.09621619546128

In [43]:
x = abs(np.random.normal(size=5))

In [44]:
x

array([0.50078111, 0.78645001, 0.39839926, 1.29654005, 0.87113178])

In [49]:
y = (x  / x.sum()) * 5

In [50]:
y

array([0.64980773, 1.02048836, 0.51695823, 1.68237525, 1.13037044])

In [51]:
y.sum()

5.0

In [ ]:
 5 / s_factor